### ISSUE TITLE
Heads-up: UB due to misuse of mem::uninitialized will soon lead to panic

### ISSUE THREAD

**Issue by RalfJung** [bugaevc/pipe-channel#1]
[Here](https://github.com/bugaevc/pipe-channel/blob/7b950b2693b018c62aabefc1e316dd7d089d40b0/src/lib.rs#L286), this crate causes UB by ["Producing an invalid value"](https://doc.rust-lang.org/reference/behavior-considered-undefined.html). Concretely, it produces a value of an arbitrary  type with `mem::uninitialized()`. In the near future the call to `mem::uninitialized()` [will panic to avoid UB](https://github.com/rust-lang/rust/pull/66059), and [our crater run](https://github.com/rust-lang/rust/pull/66059#issuecomment-575164263) determined that this crate will be affected.

`mem::uninitialized()` is deprecated since Rust 1.39. The intended replacement is [`MaybeUninit`](https://doc.rust-lang.org/core/mem/union.MaybeUninit.html), which tracks the possibility of uninitialized values at the type level to make sure the compiler does not make any false assumptions.

**Comment by bugaevc** [comment]
Hi! Thanks for the heads-up, I wanted to rewrite this code for quite some time already :slightly_smiling_face:
